EasyShoping/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('components.urls')),
    path('', include('authentication.urls')),
]

urlpatterns += staticfiles_urlpatterns()

components/urls.py
from django.urls import path
from .views import (
    ProductView, 
    ProductDetailView, 
    MobileView, 
    AddToCartView, 
    ShowCartsView,
    plus_cart,
    minus_cart,
    buy_now,
    delete_cart,
    checkout_view,
    order_done,
    order,
    orderplaced, 
    laptop_list)
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'components'
urlpatterns = [
    path('', ProductView.as_view(), name='product'),
    path('detial/<int:pk>', ProductDetailView.as_view(),name='detail'),
    path('mobile/', MobileView.as_view(), name="mobile"),
    path('mobile/<slug:data>/', MobileView.as_view(), name="mobile-data"),
    path('add-to-cart/', AddToCartView.as_view(), name="addtocart"),
    path('carts/', ShowCartsView.as_view(), name='carts'),
    path('pluscart/', plus_cart),
    path('minuscart/', minus_cart),
    path('buy-now/<int:pk>/', buy_now, name="buy_now"),
    path('delete-cart/', delete_cart, name='delete_cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('orderdone/', order_done, name="order_done"),
    path('order/', order, name="order"),
    path('orderplaced/', orderplaced, name='orderplaced'),
    path('laptops/', laptop_list, name="laptop"),
    path('laptops/<slug:data>/', laptop_list, name="laptop_data"),
    path('topwear/', views.top_wear, name="topwear"),
    path('topwear/<slug:data>', views.top_wear, name="topwear_data"),
    path('bottomwear/', views.bottom_wear, name="bottomwear"),
    path('bottomwear/<slug:data>', views.bottom_wear, name="bottomwear_data"),
    path('prodplus/', views.product_plus),
    path('prodminus/', views.product_minus),
    path('search-product/', views.search_view, name="search")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

components/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

STATE_CHOICE = (
    ('Dhaka', 'Dhaka'),
    ('Khulna', 'Khulna'),
    ('Rajshahi', 'Rajshahi'),
    ('Chittagong', 'Chittagong'),
    ('Sylhet', 'Sylhet'),
    ('Barisal', 'Barisal'),
    ('Rangpur', 'Rangpur'),
)
class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    locality = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    zipcode = models.IntegerField()
    state = models.CharField(choices=STATE_CHOICE, max_length=50)
    
    def __str__(self):
        return str(self.id)
    
    
CATEGORY_CHOICES = (
    ('Laptop', 'Laptop'),
    ('Mobile', 'Mobile'),
    ('Top Wear', 'Top Wear'),
    ('Bottom Wear', 'Bottom Wear'),
)

class Product(models.Model):
    title = models.CharField(max_length=200)
    selling_price = models.FloatField()
    discount_price = models.FloatField()
    description = models.TextField()
    brand = models.CharField(max_length=50)
    category = models.CharField(choices= CATEGORY_CHOICES, max_length=100)
    product_image = models.ImageField(upload_to='productimg')
    
    def __str__(self):
        return str(self.id)

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)
    
STATUS_CHOICES = (
    ('Accepted', 'Accepted'),
    ('Packed', 'Packed'),
    ('On The Way', 'On The Way'),
    ('Delivered', 'Delivered'),
    ('Cancel', 'Cancel'),
)

class OrderPlaced(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=50, default='Pending')
    

components/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Product, Customer, Cart, OrderPlaced
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.
quan = 1
class ProductView(View):
    def get(self, request):
        topwears = Product.objects.filter(category = 'Top Wear')
        bottomwears = Product.objects.filter(category = 'Bottom Wear')
        mobile = Product.objects.filter(category = 'Mobile')
        laptop = Product.objects.filter(category = 'Laptop')
        context = {
            "topwears" : topwears,
            "bottomwears" : bottomwears,
            'mobile' : mobile,
            'laptop' : laptop
        }
        return render(request, 'comp/home.html', context)

class ProductDetailView(View):
    def get(self, request, pk):
        global quan
        quan = 1
        product = Product.objects.get(pk=pk)
        product_exit = False
        if request.user.is_authenticated:
            product_exit = Cart.objects.filter(Q(product=pk)&Q(user=request.user)).exists()
        context = {
            'product':product,
            'product_exit' : product_exit
        }
        return render(request, 'comp/detail.html', context)

class MobileView(View):
    def get(self, request, data=None):
        if(data==None):
           mobile = Product.objects.filter(category='Mobile')
        else:
            mobile = Product.objects.filter(category='Mobile').filter(brand=data)
        context = {
            'mobile' : mobile,
        }
        return render(request, 'comp/mobile.html', context)

@method_decorator(login_required, name="dispatch")
class AddToCartView(View):
    def get(self, request):
        global quan
        user = request.user
        product_id = request.GET.get('prod_id')
        product = Product.objects.get(pk=product_id)
        Cart(user=user, product=product, quantity=quan).save()
        return redirect('/carts/')

@method_decorator(login_required, name="dispatch")
class ShowCartsView(View):
    def get(self, request):
        if request.user.is_authenticated:
            user = request.user
            carts = Cart.objects.filter(user=user)
            amount = 0.0
            shipping_cost = 0.0
            total_amount = 0.0
            message = ""
            cart_products = [prod for prod in Cart.objects.all() if prod.user == user]
            if cart_products:
                for prod in cart_products:
                    amount += prod.product.selling_price*prod.quantity
                shipping_cost += 80.0
            else:
                message += "You have no product in your cart!"
            total_amount += amount+shipping_cost
            context = {
                'carts':carts,
                'amount':amount,
                'shipping_cost':shipping_cost,
                'total_amount':total_amount,
                'message':message,
            }
        return render(request, 'comp/addtocart.html', context)

@login_required
def plus_cart(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product = prod_id) & Q(user = request.user))
        c.quantity += 1
        c.save()
        amount = 0.0
        shipping_cost = 0.0
        total_amount = 0.0
        cart_products = [prod for prod in Cart.objects.all() if prod.user == request.user]
        if cart_products:
            for prod in cart_products:
                amount += prod.product.selling_price*prod.quantity
            shipping_cost += 80.0
        total_amount += amount+shipping_cost
        data = {
            'quantity':c.quantity,
            'amount':amount,
            'total_amount':total_amount
        }
        return JsonResponse(data)

@login_required
def minus_cart(request):
    if request.method == 'GET':
        prod_id = request.GET['prod_id']
        c = Cart.objects.get(Q(product=prod_id) & Q(user = request.user))
        if(c.quantity > 1):
            c.quantity -= 1
        c.save()
        amount = 0.0
        shipping_cost = 0.0
        total_amount = 0.0
        cart_products = [prod for prod in Cart.objects.all() if prod.user == request.user]
        if cart_products:
            for prod in cart_products:
                amount += prod.product.selling_price*prod.quantity
            shipping_cost += 80.0
        total_amount += amount+shipping_cost
        data = {
            'quantity':c.quantity,
            'amount':amount,
            'total_amount':total_amount
        }
        return JsonResponse(data)

@login_required
def delete_cart(request):
    if request.method == 'GET':
        cart_id = request.GET.get("cart_id")
        print(cart_id)
        c = Cart.objects.get(Q(id = cart_id) & Q(user = request.user))
        c.delete()
    return redirect("/carts/")

@login_required       
def buy_now(request, pk):
    product = Product.objects.get(pk=pk)
    amount = product.selling_price*quan
    shipping_cost = 80.0
    total_amount = amount + shipping_cost
    customers = Customer.objects.filter(user=request.user)
    context = {
        'product':product,
        'amount' : amount,
        'customers':customers,
        'shipping_cost' : shipping_cost,
        'total_amount' : total_amount,
        'quantity': quan,
    }
    return render(request, 'comp/buy.html', context)

def product_plus(request):
    global quan
    quan =  int(request.GET["q"])
    data = {
        'quan': quan
    }
    return JsonResponse(data)

def product_minus(request):
    global quan
    quan = int(request.GET["q"])
    data = {
        'quan': quan
    }
    return JsonResponse(data)

@login_required
def checkout_view(request):
    user = request.user
    carts = Cart.objects.filter(user=user)
    customers = Customer.objects.filter(user=user)
    amount = 0.0
    shipping_cost = 0.0
    total_amount = 0.0
    if carts:
        for prod in carts:
            amount += prod.product.selling_price*prod.quantity
        shipping_cost += 80.0
    total_amount += amount+shipping_cost
    context = {
        'carts':carts,
        'customers' : customers,
        'amount':amount,
        'shipping_cost':shipping_cost,
        'total_amount':total_amount,
    }
    return render(request, 'comp/checkout.html', context)

@login_required
def order_done(request):
    cusid = request.GET["customer"]
    customer = Customer.objects.get(pk=cusid)
    user = request.user
    carts = Cart.objects.filter(user=user)
    for cart in carts:
        order = OrderPlaced(user=user, customer=customer, product=cart.product, quantity=cart.quantity)
        order.save()
        carts.delete()
    return redirect("components:order")

@login_required
def order(request):
    user = request.user
    products = OrderPlaced.objects.filter(user = user)
    message = ""
    if not products:
        message += "You don't order any product yet!"
    context = {
        'carts' : products,
        'message' : message,
    }
    return render(request, 'comp/orderdone.html', context)

@login_required
def orderplaced(request):
    prod_id = request.GET["prod_id"]
    cust_id = request.GET["customer"]
    product = Product.objects.get(pk=prod_id)
    customer = Customer.objects.get(pk=cust_id)
    user = request.user
    OrderPlaced(user=user, customer=customer, product=product, quantity=quan).save()
    return redirect("components:order")

def laptop_list(request, data=None):
    if(data==None):
        laptops = Product.objects.filter(category='Laptop')
    else:
        laptops = Product.objects.filter(category='Laptop').filter(brand=data)
    return render(request, "comp/laptop.html", {"laptops":laptops})

def top_wear(request, data=None):
    if(data==None):
        fashion = Product.objects.filter(category="Top Wear")
    else:
        fashion = Product.objects.filter(category="Top Wear").filter(brand=data)
    return render(request, "comp/topwear.html", {"fashion":fashion})

def bottom_wear(request, data=None):
    if(data==None):
        fashion = Product.objects.filter(category="Bottom Wear")
    else:
        fashion = Product.objects.filter(category="Bottom Wear").filter(brand=data)
    return render(request, 'comp/bottomwear.html', {"fashion":fashion})

def search_view(request):
    if request.method == "GET":
        search = request.GET.get("search")
        if search=="":
            return redirect("components:product")
        products = Product.objects.filter(
            Q(title__icontains=search) | 
            Q(brand__icontains=search) |
            Q(description__icontains=search) |
            Q(category__icontains=search))
        message=""
        if not products:
            message = "your search doesn't match any products!"
        context = {
            'products':products,
            'src':search,
            'message' : message
        }
        return render(request, "comp/search.html", context)
        

components/templates/comp/addtocart.html
{% extends 'comp/base.html' %}
{% block title %}cart{% endblock title %}
{% block style %}
    <style>
        a.ca{
            color:red;
        }
    </style>
{% endblock style %}
{% block main-content %}
{% load static %}
<div class="block">
    <div class="cart-block">
        <h3 class="msg">{{message}}</h3>
        {% for cart in carts %}
        <div class="cart-content">
            <div class="des">
            <a href="{% url 'components:detail' cart.product.id %}">
            <img src="{{ cart.product.product_image.url}}"/>
            <div class="prod-title">
                <h3>{{cart.product.title}}</h3>
                <p class="prod-des">Product Description: {{cart.product.description}}</p>
            </div>
            </a>
            </div>
            <div class="price">
            <p class="tk">ট: {{cart.product.selling_price}}</p>
            <p class="dis"><del>ট: {{cart.product.discount_price}}</del></p>
            <p class="quantity">Quantity: <span class="add min cart-minus" pid="{{cart.product.id}}"><i class="material-icons">remove</i></span>
                <span id="{{cart.product.id}}">{{cart.quantity}}</span><span class="add cart-plus" pid="{{cart.product.id}}"><i class="material-icons">add</i></span></p>
            <form action="/delete-cart/">
                <input type="hidden" name="cart_id" value="{{cart.id}}"/>
                <input type="submit" value="Remove Item" class="rbtn"/>
            </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="category-block">
        <h3>Total Product Price</h3>
        <hr/>
        <p>Ammount: <span id="amount">{{amount}}</span></p>
        <p>Shipping Cost: {{shipping_cost}}</p>
        <hr/>
        <p>Total Ammount: <span id="total_amount">{{total_amount}}</span></p>
        {% if message %}
            <p class="rbtn pro check" id="inactive">Process To Checkout</p>
        {% else %}
            <a href="{% url 'components:checkout' %}" class="rbtn pro check">Process To Checkout</a>
        {% endif %}
    </div>
</div>
{% endblock %}

components/templates/comp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EasyShopping | {% block title %} {% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'comp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'auth/css/login.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="body">
    <nav class="nav">
        <h2><span class="logo">E</span>asy<span class="logo">S</span>hopping</h2>
        <div id="menutap">
        <div class="nav-menu">
            <div class="static-menu">
            <a href="{% url 'components:product' %}" class="home">Home</a>
            <div id="tec-toggle">
                <a onclick="tecDropDown()" class="dropdownclick tec">Technologies<i class="material-icons">arrow_drop_down</i></a>
                <div class="tec-dropdown">
                    <a href="{% url 'components:mobile' %}" id="tec-dropdown-menu">Mobile</a>
                    <a href="{% url 'components:laptop' %}" id="tec-dropdown-menu">Laptop</a>
                </div>
            </div>
            <div id="toggle">
            <a onclick="fashionDropDown()" class="dropdownclick fash">Fashion <i class="material-icons">arrow_drop_down</i></a>
            <div class="dropdown">
                <a href="{% url 'components:topwear' %}" id="dropdown-menu">Top Wears</a>
                <a href="{% url 'components:bottomwear' %}" id="dropdown-menu">Bottom Wears</a>
            </div>
            </div>
            </div>
            <div class="dynamic-menu">
            {% if request.user.is_authenticated %}
                <a href="{% url 'components:carts' %}" class="ca">Cart</a>
                <a href="{% url 'components:order' %}" class="or">Order</a>

                <div id="pro-toggle">
                    <a onclick="proDropDown()" class="dropdownclick pr">{{request.user}}<i class="material-icons">arrow_drop_down</i></a>
                    <div class="pro-dropdown">
                        <a href="{% url 'profile' %}" id="dropdown-menu">Profile</a>
                        <a href="{% url 'user-logout' %}" id="dropdown-menu">Logout</a>
                        <a href="{% url 'change-pass' %}" id="dropdown-menu">Change Password</a>
                        <a href="{% url 'password_reset' %}" id="dropdown-menu">Reset Password</a>
                    </div>
                </div>
            {% else %}
            <a href="{% url 'user-login' %}" class="lo">Login</a>
            <a href="{% url 'user-register' %}" class="re">Register</a>
            {% endif %}
            </div>
        </div>
        <i onclick="tapDropDown()" class="material-icons tap-menu">menu</i>
    </div>
    </nav>
    <form action="/search-product/" id="search-box">
        {% csrf_token %}
        <input type="text" class="search" name="search" placeholder="Search in EasyShopping"/>
        <input type="submit" value="Search" class="search-btn"/>
    </form>
    {% block main-content %}
    {% endblock main-content %}
    <footer>
        <div class="footer-info info1">
            <h3 class="footer-header">Customer Care</h3>
            <p>Help Center</p>
            <p>How to Buy</p>
            <p>Returns & Refunds</p>
            <p>Contact Us</p>
            <p>Terms & Conditions</p>
        </div>
        <div class="footer-info">
            <h3 class="footer-header">EasyShopping</h3>
            <p>About EasyShopping</p>
            <p>Digital Payments</p>
            <p>EasyShopping Cares</p>
            <p>Privacy Policy</p>
            <p>Easyshopping App</p>

        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{% static 'comp/js/mysite.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        $('.owl-one').owlCarousel({
            loop:true,
            margin:10,
            nav:false,
            autoplay:true,
            autoplaytimeout:5000,
            animateOut: 'fadeOut', 
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:1
                },
                1000:{
                    items:1
                }
            }
        })
        $('.owl-two').owlCarousel({
            loop:false,
            margin:10,
            nav:false,
            stagePadding:40,
            dots:false,
            responsive:{
                0:{
                    items:2
                },
                600:{
                    items:3
                },
                800:{
                    items:3
                },
                900:{
                    items:4
                },
                1000:{
                    items:5
                },
                1200:{
                    items:6
                },
            }
        })
    </script>
</div>
</body>
</html>

components/templates/comp/bottomwear.html
{% extends 'comp/base.html'%}
{% load static %}
{% block title %}TopWear{% endblock title %}
{% block style %}
        <style>
            a.fash{
                color:red;
            }
        </style>
    {% endblock style %}
{% block main-content%}
<div class="mobile-container">
    <div class="category-search">
        <h3>Brand</h3>
        <hr/>
        <a href="{% url 'components:bottomwear' %}" class="category">All BottomWear</a>
        <a href="{% url 'components:bottomwear_data' 'DUDESTYLE' %}" class="category">DUDE STYLE</a>
        <a href="{% url 'components:bottomwear_data' 'IELGY'%}" class="category">IELGY</a>
        <a href="{% url 'components:bottomwear_data' 'SMUG'%}" class="category">SMUG</a>
        <a href="{% url 'components:bottomwear_data' 'GoodMan'%}" class="category">GoodMan</a>
    </div>
    <div class="mobile-block">
        {% for top in fashion %}
        <ul class="product-design">
            <a href="{% url 'components:detail' top.id %}">
            <img src="{{ top.product_image.url}}"/>
            <li>{{top.title}}</li>
            <li class="tk">ট: {{top.selling_price}}</li>
            <li class="dis"><del>ট: {{top.discount_price}}</del></li>
        </a>
        </ul>
        {% endfor %}
    </div>
</div>
{% endblock main-content%}

components/templates/comp/checkout.html
{% extends 'comp/base.html' %}
{% block title %}cart{% endblock title %}
{% block main-content %}
{% load static %}
<div class="block">
    <div class="cart-block">
        <h3>{{message}}</h3>
        {% for cart in carts %}
        <div class="cart-content">
            <div class="des">
            <a href="{% url 'components:detail' cart.product.id %}">
            <img src="{{ cart.product.product_image.url}}"/>
            <div class="prod-title">
                <h3>{{cart.product.title}}</h3>
                <p class="prod-des">Product Description: {{cart.product.description}}</p>
            </div>
            </a>
            </div>
            <div class="price">
            <p class="tk">ট: {{cart.product.selling_price}}</p>
            <p class="dis"><del>ট: {{cart.product.discount_price}}</del></p>
            <p class="quantity">Quantity: {{cart.quantity}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="placeorder-block">
        <h3>Customer Address</h3>
        <form action="{% url 'components:order_done' %}">
        {% csrf_token %}
        <div class="address">
        {% for customer in customers %}
        <div class="address-info">
            <input class="radio" id="customer{{forloop.counter}}" 
                type="radio" name="customer" value="{{customer.id}}"/>
            <label for="radio">
            <h4>{{customer.name}}</h4>
            <p>{{customer.locality}}, {{customer.city}}, {{customer.zipcode}}, {{customer.state}}</p>
            </label>
        </div>
        {% endfor %}
        </div>
        <div class="addressorder-block">
        <h3>Total Product Price</h3>
        <p>Ammount: <span id="amount">{{amount}}</span></p>
        <p class="cost">Shipping Cost:<span> {{shipping_cost}}</span></p>
        <hr/>
        <p>Total Ammount: <span id="total_amount">{{total_amount}}</span></p>
        <input type="submit" class="rbtn pro" value="Place Order"/>
        </div>
    </form>
    </div>
</div>
{% endblock %}

components/templates/comp/laptop.html
{% extends 'comp/base.html'%}
{% load static %}
{% block title %}Laptop{% endblock title %}
{% block style %}
        <style>
            a.tec{
                color:red;
            }
        </style>
    {% endblock style %}
{% block main-content%}
<div class="mobile-container">
    <div class="category-search">
        <h3>Brand</h3>
        <hr/>
        <a href="{% url 'components:laptop' %}" class="category">All Laptop</a>
        <a href="{% url 'components:laptop_data' 'HP' %}" class="category">HP</a>
        <a href="{% url 'components:laptop_data' 'ASUS'%}" class="category">ASUS</a>
        <a href="{% url 'components:laptop_data' 'Apple'%}" class="category">Apple</a>
    </div>
    <div class="mobile-block">
        {% for top in laptops %}
        <ul class="product-design">
            <a href="{% url 'components:detail' top.id %}">
            <img src="{{ top.product_image.url}}"/>
            <li>{{top.title}}</li>
            <li class="tk">ট: {{top.selling_price}}</li>
            <li class="dis"><del>ট: {{top.discount_price}}</del></li>
        </a>
        </ul>
        {% endfor %}
    </div>
</div>
{% endblock main-content%}

components/templates/comp/mobile.html
{% extends 'comp/base.html'%}
{% load static %}
{% block title %}Mobile{% endblock title %}
{% block style %}
        <style>
            a.tec{
                color:red;
            }
        </style>
    {% endblock style %}
{% block main-content%}
<div class="mobile-container">
    <div class="category-search">
        <h3>Brand</h3>
        <hr/>
        <a href="{% url 'components:mobile' %}" class="category">All Mobile</a>
        <a href="{% url 'components:mobile-data' 'Apple' %}" class="category">Apple</a>
        <a href="{% url 'components:mobile-data' 'Samsung'%}" class="category">Samsung</a>
    </div>
    <div class="mobile-block">
        {% for top in mobile %}
        <ul class="product-design">
            <a href="{% url 'components:detail' top.id %}">
            <img src="{{ top.product_image.url}}"/>
            <li>{{top.title}}</li>
            <li class="tk">ট: {{top.selling_price}}</li>
            <li class="dis"><del>ট: {{top.discount_price}}</del></li>
        </a>
        </ul>
        {% endfor %}
    </div>
</div>
{% endblock main-content%}

components/templates/comp/topwear.html
{% extends 'comp/base.html'%}
{% load static %}
{% block title %}TopWear{% endblock title %}
{% block style %}
        <style>
            a.fash{
                color:red;
            }
        </style>
    {% endblock style %}
{% block main-content%}
<div class="mobile-container">
    <div class="category-search">
        <h3>Brand</h3>
        <hr/>
        <a href="{% url 'components:topwear' %}" class="category">All TopWear</a>
        <a href="{% url 'components:topwear_data' 'IELGY' %}" class="category">IELGY</a>
        <a href="{% url 'components:topwear_data' 'SMUG'%}" class="category">SMUG</a>
        <a href="{% url 'components:topwear_data' 'GoodMan'%}" class="category">GoodMan</a>
    </div>
    <div class="mobile-block">
        {% for top in fashion %}
        <ul class="product-design">
            <a href="{% url 'components:detail' top.id %}">
            <img src="{{ top.product_image.url}}"/>
            <li>{{top.title}}</li>
            <li class="tk">ট: {{top.selling_price}}</li>
            <li class="dis"><del>ট: {{top.discount_price}}</del></li>
        </a>
        </ul>
        {% endfor %}
    </div>
</div>
{% endblock main-content%}